### ISSUE TITLE
Unable to build own image, get_image.sh fails, image no longer available online

### ISSUE THREAD

**Issue by gemarcano** [ETHZ-TEC/RocketLogger#100]
While experimenting in building my own image using `patch_image.sh`, I received a 404 from `get_image.sh`. Specifically, it looks like
https://rcn-ee.com/rootfs/bb.org/testing/2021-06-22/buster-console/bone-eMMC-flasher-debian-10.10-console-armhf-2021-06-22-1gb.img.xz
is no longer available.

**Comment by lsigrist** [comment]
Thanks for reporting. To be less dependent on this third party managed dependency, a pre-built RocketLogger image is provided for each release, see <https://github.com/ETHZ-TEC/RocketLogger/releases>.
Latest BeagleBone images that could be used as replacement for building your own image are published in the BeagleBone forum: <https://forum.beagleboard.org/t/debian-10-x-buster-monthly-snapshots/31203>.

The `get_image.sh` script it self will soon be fixed on master with release 2.1.0 (#99).

**Comment by lsigrist** [comment]
Resolved by #99
