### ISSUE TITLE
Update documentation for release 2.0.0

### ISSUE THREAD

**Issue by lsigrist** [ETHZ-TEC/RocketLogger#20]
Update RocketLogger wiki
- [x] updated data formats
- [x] updated CLI with comparison to version 1.x
- [x] third-party project dependencies included and build dependency or installed as npm dependencies -> in-repo READMEs
- [x] FlockLab 2 integration overview
- [x] review wiki content, identify more required updates
- [x] remote system installation
- [x] update instructions v1.x -> v2.0.0, incl. data SD card setup
- [x] update calibration instruction with Python library usage
- [x] software and Python code documentation pages
- [x] new hardware button interface
- [x] update wiki home with latest links
- [ ] software architecture overview

**Comment by abiri** [comment]
Reviewed documentation in the Wiki, updated READMEs in 8052997cf98481927a98dda034af98a191832957
