### ISSUE TITLE
RocketLogger setup: does not boot from SD card by default

### ISSUE THREAD

**Issue by rdaforno** [ETHZ-TEC/RocketLogger#32]
The RocketLogger does not seem to boot from the SD card by default. Therefore, in order to flash the system image, the user button needs to be pressed while powering it up.
-> should be mentioned in the readme

**Comment by lsigrist** [comment]
Let me guess: the user button press was required when flashing a BeagleBone Black (we propose to use a BeagleBone Green). The Black and Green variants are known to have different default boot behavior. Nevertheless, the different behavior should be added to the docs.

**Comment by rdaforno** [comment]
No, it was a normal RocketLogger (bb-8) which has a BBG. Strange.

**Comment by lsigrist** [comment]
Installation troubleshooting to be covered as part of the documentation updates #20.
