### ISSUE TITLE
Pypi rocketlogger-2.0.0-py3-none-any.whl missing convert_calibration.py

### ISSUE THREAD

**Issue by gemarcano** [ETHZ-TEC/RocketLogger#33]
While upgrading my rocketlogger to v2, I did a pip install and noticed that the `convert_calibration.py` script was not installed. I downloaded the wheel from Pypi directly and inspected it , and it only included the dist info plus:
```
__init__.py
calibration.py
data.py
tests/__init__.py
tests/calibration.py
data.py
```

It looks like none of the files listed in the Manifest.in made it into the wheel (not sure how/if Manifest.in is interpreted).

**Comment by lsigrist** [comment]
The files listed in the `Manifest.in` are only considered for the source package source [1]. The sample scripts `calibrate.py`, `convert_calibration.py`, `example.py` and test data contained in the source distribution are however not considered for installation or built distributions such as wheels.
Please extract the required sample or conversion script from the source distribution `rocketlogger-2.0.0.tar.gz` [2]. Alternatively, these files can directly be downloaded from the repository [3].

[1] https://packaging.python.org/guides/distributing-packages-using-setuptools/#manifest-in
[2] https://pypi.org/project/rocketlogger/2.0.0/#files
[3] https://github.com/ETHZ-TEC/RocketLogger/tree/v2.0.0/script/python

**Comment by lsigrist** [comment]
I have reviewed and update the mentioned wiki page, hope is is now more clear how to get the script. As the generated Python docs should also be reviewed prior to a next release, I propose to keep the issue open for this purpose.

Thanks @gemarcano for reporting this shortcoming!
