### ISSUE TITLE
ADC not responsive error

### ISSUE THREAD

**Issue by rdaforno** [ETHZ-TEC/RocketLogger#36]
After a system update (`apt-get dist-upgrade`), the RocketLogger daemon does not start properly. Error message: `ADC not responsive`. 
By adding an additional delay of ~10 seconds [here](https://github.com/ETHZ-TEC/RocketLogger/blob/flocklab/software/rocketlogger/config/rocketlogger.service#L8) at the end, the problem seems to disappear.

This happens with the `flocklab` branch. Not sure whether this problem is specific to Debian 9.

[Fix added to branch `flocklab`](https://github.com/ETHZ-TEC/RocketLogger/commit/21e5db5785055214750d35c0c9196563f2d93483).

**Comment by lsigrist** [comment]
Closing the issue as not reproduced with any official release. The here described problem hinted at a different issues #50 in case of service start up problems, blocking automatic restart in case of start up problems.
