### ISSUE TITLE
Remove debug console output in Python data processing library functionality

### ISSUE THREAD

**Issue by rtrueb** [ETHZ-TEC/RocketLogger#46]
It would be helpful if the [printout](https://github.com/ETHZ-TEC/RocketLogger/blob/master/script/python/rocketlogger/data.py#L1190) of the `merge_channels` function could be disabled (either permanently, via state of the `RocketLoggerData` class, or via a function argument).

**Comment by lsigrist** [comment]
Thanks @rtrueb, this is a very good point. It is probably not the task of a data processing library to print to the console what it is doing. I'd even extend your input to any print statement in `rocketlogger.data` (see list below) and rather make sure that relevant warnings/errors are raised for unexpected behavior/failures. What do you think? Does this match your reasons for raising this issue?

* [\#772](https://github.com/ETHZ-TEC/RocketLogger/blob/master/script/python/rocketlogger/data.py#L772) - drop, this is expected user defined behavior (function arguement)
* [\#924](https://github.com/ETHZ-TEC/RocketLogger/blob/master/script/python/rocketlogger/data.py#L924) - drop, more of a debug output for expected result
* [\#1190](https://github.com/ETHZ-TEC/RocketLogger/blob/master/script/python/rocketlogger/data.py#L1190) - drop, more of a debug output for expected result

**Comment by rtrueb** [comment]
The proposed changes address my issue and make sense from my point of view.

**Comment by lsigrist** [comment]
fix verified using a942b32
